### ISSUE TITLE
Not a valid LFP File

### ISSUE THREAD

**Issue by PuneetKohli** [behnam/python-lfp-reader#7]
I'm trying to export my images from the Lytro Illum camera, and none of the commands work except `./lfp-file.py`. 

Could you please let me know if this library supports Lytro Illum photos?

**Comment by behnam** [comment]
Thanks for filing this, @PuneetKohli. I have not tried Lytro Illum myself, but based on the latest software updates on the first-get Lytro cameras, I'm almost sure that the file formats used by Lytro Illum are not supported.

I'm going ahead and closing the issue, as there are no plans for work on adding support for newer formats. If you're interested, any PRs are always welcome! :)
